image_width: 1280
image_height: 720
camera_name: table-1-camera
camera_matrix:
  rows: 3
  cols: 3
  data: [953.94424,   0.     , 651.69739,
           0.     , 953.20135, 345.27957,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.024623, -0.100074, 0.002469, 0.004024, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [943.31458,   0.     , 657.60729,   0.     ,
           0.     , 954.69519, 345.88647,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
